import type { Copy, Locale } from './i18n.js';

type ReferenceTranslation = Pick<Copy['common'],
    'reference' | 'referenceSearch' | 'referenceAll' | 'referenceFunctions' | 'referenceTypes' | 'referenceEngines' |
    'referenceSettings' | 'referenceSystem' | 'referencePopular' | 'referenceNoMatches' | 'referenceNative' |
    'referenceBundled' | 'referenceSource' | 'referenceBack' | 'referenceEntryUnavailable' | 'referenceRetry' |
    'referenceBundledNote' | 'referenceCategories' | 'referenceMatches' | 'referenceEmptyHint' | 'referenceResults' |
    'referenceInsert' | 'referenceCopy' | 'referenceSystemTable' | 'clearSearch'>;

export const referenceTranslations: Record<Exclude<Locale, 'en'>, ReferenceTranslation> = {
    de: { reference: 'Referenz', referenceSearch: 'ClickHouse durchsuchen…', referenceAll: 'Alle', referenceFunctions: 'Funktionen', referenceTypes: 'Typen', referenceEngines: 'Engines', referenceSettings: 'Einstellungen', referenceSystem: 'System', referencePopular: 'Beliebt', referenceNoMatches: 'Keine Referenzeinträge entsprechen dieser Suche.', referenceNative: 'Native ClickHouse-Referenz', referenceBundled: 'Enthaltene Demo-Referenz', referenceSource: 'QUELLE', referenceBack: 'Zurück zu den Ergebnissen', referenceEntryUnavailable: 'Dieser Eintrag ist auf dem ausgewählten Server nicht dokumentiert.', referenceRetry: 'Erneut versuchen', referenceBundledNote: 'Beispiele sind in ClickStudio enthalten.', referenceCategories: 'Referenzkategorien', referenceMatches: '{count} Treffer', referenceEmptyHint: 'Versuchen Sie einen anderen Namen oder eine andere Kategorie.', referenceResults: 'Referenzergebnisse', referenceInsert: 'Namen einfügen', referenceCopy: 'Namen kopieren', referenceSystemTable: 'Systemtabellen-Referenz', clearSearch: 'Suche löschen' },
    es: { reference: 'Referencia', referenceSearch: 'Buscar en ClickHouse…', referenceAll: 'Todo', referenceFunctions: 'Funciones', referenceTypes: 'Tipos', referenceEngines: 'Motores', referenceSettings: 'Ajustes', referenceSystem: 'Sistema', referencePopular: 'Populares', referenceNoMatches: 'No hay entradas de referencia que coincidan.', referenceNative: 'Referencia nativa de ClickHouse', referenceBundled: 'Referencia de demostración incluida', referenceSource: 'ORIGEN', referenceBack: 'Volver a los resultados', referenceEntryUnavailable: 'El servidor seleccionado no documenta esta entrada.', referenceRetry: 'Reintentar', referenceBundledNote: 'ClickStudio incluye ejemplos.', referenceCategories: 'Categorías de referencia', referenceMatches: '{count} resultados', referenceEmptyHint: 'Prueba con otro nombre o categoría.', referenceResults: 'Resultados de referencia', referenceInsert: 'Insertar nombre', referenceCopy: 'Copiar nombre', referenceSystemTable: 'Referencia de tabla del sistema', clearSearch: 'Borrar búsqueda' },
    nl: { reference: 'Referentie', referenceSearch: 'Zoek in ClickHouse…', referenceAll: 'Alle', referenceFunctions: 'Functies', referenceTypes: 'Typen', referenceEngines: 'Engines', referenceSettings: 'Instellingen', referenceSystem: 'Systeem', referencePopular: 'Populair', referenceNoMatches: 'Geen referentie-items gevonden.', referenceNative: 'Native ClickHouse-referentie', referenceBundled: 'Ingebouwde demoreferentie', referenceSource: 'BRON', referenceBack: 'Terug naar resultaten', referenceEntryUnavailable: 'Deze vermelding is niet gedocumenteerd op de gekozen server.', referenceRetry: 'Opnieuw proberen', referenceBundledNote: 'ClickStudio bevat voorbeelditems.', referenceCategories: 'Referentiecategorieën', referenceMatches: '{count} resultaten', referenceEmptyHint: 'Probeer een andere naam of categorie.', referenceResults: 'Referentieresultaten', referenceInsert: 'Naam invoegen', referenceCopy: 'Naam kopiëren', referenceSystemTable: 'Systeemtabellen-referentie', clearSearch: 'Zoekopdracht wissen' },
    zh: { reference: '参考', referenceSearch: '搜索 ClickHouse…', referenceAll: '全部', referenceFunctions: '函数', referenceTypes: '类型', referenceEngines: '引擎', referenceSettings: '设置', referenceSystem: '系统', referencePopular: '热门', referenceNoMatches: '没有匹配的参考条目。', referenceNative: 'ClickHouse 原生参考', referenceBundled: '内置演示参考', referenceSource: '来源', referenceBack: '返回结果', referenceEntryUnavailable: '所选服务器没有此条目的文档。', referenceRetry: '重试', referenceBundledNote: 'ClickStudio 内含示例条目。', referenceCategories: '参考类别', referenceMatches: '{count} 条匹配', referenceEmptyHint: '尝试其他名称或类别。', referenceResults: '参考结果', referenceInsert: '插入名称', referenceCopy: '复制名称', referenceSystemTable: '系统表参考', clearSearch: '清除搜索' },
    ru: { reference: 'Справочник', referenceSearch: 'Поиск в ClickHouse…', referenceAll: 'Все', referenceFunctions: 'Функции', referenceTypes: 'Типы', referenceEngines: 'Движки', referenceSettings: 'Настройки', referenceSystem: 'Система', referencePopular: 'Популярное', referenceNoMatches: 'Подходящие записи не найдены.', referenceNative: 'Справочник ClickHouse', referenceBundled: 'Встроенный демо-справочник', referenceSource: 'ИСТОЧНИК', referenceBack: 'Вернуться к результатам', referenceEntryUnavailable: 'На выбранном сервере нет документации для этой записи.', referenceRetry: 'Повторить', referenceBundledNote: 'В ClickStudio есть примеры записей.', referenceCategories: 'Категории справочника', referenceMatches: 'Совпадений: {count}', referenceEmptyHint: 'Попробуйте другое имя или категорию.', referenceResults: 'Результаты справочника', referenceInsert: 'Вставить имя', referenceCopy: 'Копировать имя', referenceSystemTable: 'Описание системной таблицы', clearSearch: 'Очистить поиск' },
};

type ReferenceCatalogTranslation = Pick<Copy['common'], 'referenceFormats' | 'referenceSql' | 'referenceBrowse' | 'referenceBundled' | 'referenceBundledNote'>;

export const referenceCatalogTranslations: Record<Exclude<Locale, 'en'>, ReferenceCatalogTranslation> = {
    de: { referenceFormats: 'Formate', referenceSql: 'SQL', referenceBrowse: 'Vollständigen Katalog durchsuchen', referenceBundled: 'Offline-ClickHouse-Referenz', referenceBundledNote: 'Vollständiger Offline-Katalog mit SQL-Beispielen.' },
    es: { referenceFormats: 'Formatos', referenceSql: 'SQL', referenceBrowse: 'Explorar catálogo completo', referenceBundled: 'Referencia offline de ClickHouse', referenceBundledNote: 'Catálogo offline completo con ejemplos SQL.' },
    nl: { referenceFormats: 'Formaten', referenceSql: 'SQL', referenceBrowse: 'Volledige catalogus bekijken', referenceBundled: 'Offline ClickHouse-referentie', referenceBundledNote: 'Volledige offlinecatalogus met SQL-voorbeelden.' },
    zh: { referenceFormats: '格式', referenceSql: 'SQL', referenceBrowse: '浏览完整目录', referenceBundled: '离线 ClickHouse 参考', referenceBundledNote: '完整离线目录，包含 SQL 示例。' },
    ru: { referenceFormats: 'Форматы', referenceSql: 'SQL', referenceBrowse: 'Весь каталог', referenceBundled: 'Офлайн-справочник ClickHouse', referenceBundledNote: 'Полный офлайн-каталог с примерами SQL.' },
};

type ObjectExplorerTranslation = Pick<Copy['common'],
    'objects' | 'objectSearch' | 'objectCount' | 'noObjectsMatch' | 'noObjectsMatchHint' | 'noObjectsAvailable' | 'noObjectsAvailableHint' | 'views' | 'dictionaries' | 'columns' |
    'previewRows' | 'generateSelect' | 'newTable' | 'insertRow' | 'deleteTable' | 'insertName' | 'copyName' | 'copied'>;

export const objectExplorerTranslations: Record<Exclude<Locale, 'en'>, ObjectExplorerTranslation> = {
    de: { objects: 'Objekte', objectSearch: 'Objekte, Spalten, Engines und Indizes suchen…', objectCount: '{count} OBJEKTE', noObjectsMatch: 'Keine Objekte entsprechen dieser Suche.', noObjectsMatchHint: 'Versuchen Sie einen anderen Namen, Typ, eine andere Engine, einen anderen Index oder eine andere Spalte.', noObjectsAvailable: 'Keine Objekte gefunden.', noObjectsAvailableHint: 'Für diese Verbindung sind keine Tabellen, Views oder Wörterbücher sichtbar.', views: 'Views', dictionaries: 'Wörterbücher', columns: 'Spalten', previewRows: 'Zeilen ansehen', generateSelect: 'SELECT erzeugen', newTable: 'Neue Tabelle', insertRow: 'Zeile einfügen', deleteTable: 'Tabelle löschen', insertName: 'Name einfügen', copyName: 'Name kopieren', copied: 'Kopiert' },
    es: { objects: 'Objetos', objectSearch: 'Buscar objetos, columnas, motores e índices…', objectCount: '{count} OBJETOS', noObjectsMatch: 'Ningún objeto coincide con esta búsqueda.', noObjectsMatchHint: 'Prueba con otro nombre, tipo, motor, índice o columna.', noObjectsAvailable: 'No se encontraron objetos.', noObjectsAvailableHint: 'No hay tablas, vistas ni diccionarios visibles en esta conexión.', views: 'Vistas', dictionaries: 'Diccionarios', columns: 'Columnas', previewRows: 'Ver filas', generateSelect: 'Generar SELECT', newTable: 'Nueva tabla', insertRow: 'Insertar fila', deleteTable: 'Eliminar tabla', insertName: 'Insertar nombre', copyName: 'Copiar nombre', copied: 'Copiado' },
    nl: { objects: 'Objecten', objectSearch: 'Objecten, kolommen, engines en indexen zoeken…', objectCount: '{count} OBJECTEN', noObjectsMatch: 'Geen objecten komen overeen met deze zoekopdracht.', noObjectsMatchHint: 'Probeer een andere naam, type, engine, index of kolom.', noObjectsAvailable: 'Geen objecten gevonden.', noObjectsAvailableHint: 'Er zijn geen tabellen, views of woordenboeken zichtbaar voor deze verbinding.', views: 'Views', dictionaries: 'Woordenboeken', columns: 'Kolommen', previewRows: 'Rijen bekijken', generateSelect: 'SELECT genereren', newTable: 'Nieuwe tabel', insertRow: 'Rij invoegen', deleteTable: 'Tabel verwijderen', insertName: 'Naam invoegen', copyName: 'Naam kopiëren', copied: 'Gekopieerd' },
    zh: { objects: '对象', objectSearch: '搜索对象、列、引擎和索引…', objectCount: '{count} 个对象', noObjectsMatch: '没有匹配的对象。', noObjectsMatchHint: '请尝试其他名称、类型、引擎、索引或列。', noObjectsAvailable: '未找到对象。', noObjectsAvailableHint: '此连接中没有可见的表、视图或字典。', views: '视图', dictionaries: '字典', columns: '列', previewRows: '预览行', generateSelect: '生成 SELECT', newTable: '新建表', insertRow: '插入行', deleteTable: '删除表', insertName: '插入名称', copyName: '复制名称', copied: '已复制' },
    ru: { objects: 'Объекты', objectSearch: 'Поиск объектов, столбцов, движков и индексов…', objectCount: 'ОБЪЕКТОВ: {count}', noObjectsMatch: 'Нет объектов, соответствующих поиску.', noObjectsMatchHint: 'Попробуйте другое имя, тип, движок, индекс или столбец.', noObjectsAvailable: 'Объекты не найдены.', noObjectsAvailableHint: 'В этом подключении не видно таблиц, представлений или словарей.', views: 'Представления', dictionaries: 'Словари', columns: 'Столбцы', previewRows: 'Просмотр строк', generateSelect: 'Создать SELECT', newTable: 'Новая таблица', insertRow: 'Вставить строку', deleteTable: 'Удалить таблицу', insertName: 'Вставить имя', copyName: 'Копировать имя', copied: 'Скопировано' },
};
